{% set name = "BathyReq" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bathyreq-{{ version }}.tar.gz
  sha256: 261422f0dae837fcbe6f698f8951044e259331b7d9dbe12b9d070a92ddce8948

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - python-dotenv
    - rasterio
    - requests
    - scipy

test:
  imports:
    - bathyreq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/bathyreq/
  summary: A Python package for querying public bathymetric data sources
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
